apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tellytv.secrets.defaultName" . }}
  labels:
    {{- include "tellytv.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.secrets.secret }}